version: '3'

services:
  apache:
    build: .  # construcción usando Dockerfile
    container_name: apache-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
      - ./css/:/usr/local/apache2/htdocs/css/
      - ./scss/:/usr/local/apache2/htdocs/scss/
      - ./tf/certificate.crt:/usr/local/apache2/conf/certificate.crt
      - ./tf/ca_bundle.crt:/usr/local/apache2/conf/ca_bundle.crt
      - ./tf/private.key:/usr/local/apache2/conf/private.key
      - ./tf/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
    depends_on:
      - ldap
    environment:
      - VIRTUAL_HOST=neikap.work.gd  # para que apache pueda servir este dominio
      - VIRTUAL_PORT=443  # puerto seguro para la comunicación SSL
  
  ldap:
    image: osixia/openldap:latest
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "Mi Empresa"
      LDAP_DOMAIN: "neikap.work.gd"
      LDAP_ADMIN_PASSWORD: "adminpass"
      LDAP_ROOTDN: "cn=admin,dc=neikap,dc=work,dc=gd"
      LDAP_LOG_LEVEL: "256"
      LDAP_USERS: "cn=nerea,dc=neikap,dc=work,dc=gd"
      LDAP_PASSWORDS: "nereapass"
    ports:
      - "389:389"
      - "636:636"
    restart: always
